# Generated by Django 4.2.7 on 2024-01-15 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_general', '0004_subject_subjectclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=255)),
                ('Dob', models.DateField()),
                ('Mob', models.PositiveIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Join_date', models.DateField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('Barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('Dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.department')),
                ('Des_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.designation')),
                ('Employee_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.emp_category')),
                ('Qual_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation_id', models.DecimalField(decimal_places=2, max_digits=10)),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('Designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.designation')),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('Designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.department')),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee_registration')),
            ],
        ),
        migrations.CreateModel(
            name='CSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cls_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.master_class')),
                ('Div_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.division')),
                ('Emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.employee_registration')),
                ('Sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.subject')),
            ],
        ),
    ]
