# Generated by Django 4.2.7 on 2024-01-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_registration',
            name='Barcode',
        ),
        migrations.RemoveField(
            model_name='employee_registration',
            name='Photo',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='Salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
