# Generated by Django 4.2.7 on 2024-01-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0003_employee_registration_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_department',
            name='To_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_designation',
            name='To_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_salary',
            name='To_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
