# Generated by Django 4.2.7 on 2024-01-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0004_alter_employee_department_to_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_department',
            old_name='Designation_id',
            new_name='Department_id',
        ),
        migrations.RenameField(
            model_name='employee_salary',
            old_name='Designation_id',
            new_name='Salary',
        ),
    ]
