# Generated by Django 4.2.7 on 2024-01-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_employee', '0005_rename_designation_id_employee_department_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_registration',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
