# Generated by Django 4.2.7 on 2024-01-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_general', '0002_rename_designation_area_emp_category_employee_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_category',
            name='Employee_Area',
            field=models.IntegerField(choices=[(1, 'Accountant'), (2, 'Cafeteria'), (3, 'Librarian'), (4, 'Teacher'), (5, 'Other')]),
        ),
    ]
