# Generated by Django 4.2.7 on 2024-01-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_general', '0003_alter_emp_category_employee_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=100)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.master_class')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_general.subject')),
            ],
        ),
    ]
